language: go
sudo: required
dist: trusty
mono: latest
os: linux
dotnet: 1.0.0-preview2-003131
services: docker
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - python-pip
before_install:
  - sudo pip install awscli
branches:
  only:
    - master
script:
  # Get the last version of dotnet core and build project
  - dotnet restore
  - dotnet publish netcorebuild

  ## PUSH into ECR
  - aws --version
  - aws sts get-caller-identity
  - eval $(aws ecr get-login --region eu-west-1)
  #build the image
  - docker build --no-cache -t netcorebuild_app .
  #tag the image
  - docker tag netcorebuild_app:latest $AWS_USER_NAME.dkr.ecr.eu-west-1.amazonaws.com/pe/demo:latest
  #push the image to the repository
  - docker push $AWS_USER_NAME.dkr.ecr.eu-west-1.amazonaws.com/pe/demo:latest